dedraks_user_manager:
    resource: "@DedraksUserManagerBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

cadpaz:
    resource: "@CadpazBundle/Resources/config/routing.yml"
    prefix:   /
    
dedraks_config:
    resource: "@DedraksConfigBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
