config_user:
    path:     /
    defaults: { _controller: "CadpazBundle:User:index" }

config_user_show:
    path:     /{id}/show
    defaults: { _controller: "CadpazBundle:User:show" }

config_user_new:
    path:     /new
    defaults: { _controller: "CadpazBundle:User:new" }

config_user_create:
    path:     /create
    defaults: { _controller: "CadpazBundle:User:create" }
    methods:  POST

config_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "CadpazBundle:User:edit" }

config_user_update:
    path:     /{id}/update
    defaults: { _controller: "CadpazBundle:User:update" }
    methods:  [POST, PUT]

config_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "CadpazBundle:User:delete" }
    methods:  [POST, DELETE]
