cadpaz_config_user:
    resource: "@CadpazBundle/Resources/config/routing/user.yml"
    prefix:   /config/user

# Rotas para o controlador Pessoa
pessoa_index:
    path:     /
    defaults: { _controller: CadpazBundle:Pessoa:index }

user_info:
    path:     /user/{user}/info
    defaults: { _controller: CadpazBundle:Pessoa:userInfo }
    options:
        expose: true

pessoa_list:
    path:     /pessoa/list
    defaults: { _controller: CadpazBundle:Pessoa:list }
    options:
        expose: true

pessoa_busca:
    path:     /pessoa/busca
    defaults: { _controller: CadpazBundle:Pessoa:busca }
    options:
        expose: true

pessoa_new:
    path:     /pessoa/new
    defaults: { _controller: CadpazBundle:Pessoa:new }
    options:
        expose: true
        
pessoa_edit:
    path:     /pessoa/{id}/edit
    defaults: { _controller: CadpazBundle:Pessoa:edit }
    options:
        expose: true

pessoa_view:
    path:     /pessoa/{id}/view
    defaults: { _controller: CadpazBundle:Pessoa:view }
    options:
        expose: true

pessoa_titulo_new:
    path:     /pessoa/{id}/titulo/new
    defaults: { _controller: CadpazBundle:Pessoa:newTitulo }
    options:
        expose: true
        
pessoa_titulo_del:
    path:     /pessoa/{id}/titulo/del
    defaults: { _controller: CadpazBundle:Titulo:delete }
    options:
        expose: true
        
pessoa_rg_new:
    path:     /pessoa/{id}/rg/new
    defaults: { _controller: CadpazBundle:Pessoa:newRg }
    options:
        expose: true

pessoa_rg_del:
    path:     /pessoa/{id}/rg/del
    defaults: { _controller: CadpazBundle:RG:delete }
    options:
        expose: true
        
        
pessoa_pis_new:
    path:     /pessoa/{id}/pis/new
    defaults: { _controller: CadpazBundle:Pessoa:newPis }
    options:
        expose: true
        
pessoa_ctps_new:
    path:     /pessoa/{id}/ctps/new
    defaults: { _controller: CadpazBundle:CTPS:newCtps }
    options:
        expose: true

pessoa_ctps_del:
    path:     /pessoa/{id}/ctps/del
    defaults: { _controller: CadpazBundle:CTPS:delete }
    options:
        expose: true

# Fim das rotas para o controlador Pessoa

# Rotas para o controlador CTPS
ctps_view:
    path:     /ctps/{pessoa_id}/view
    defaults: { _controller: CadpazBundle:CTPS:view }

ctps_new:
    path:     /ctps/{pessoa_id}/new
    defaults: { _controller: CadpazBundle:CTPS:new }

# Fim das rotas pra o controlador CTPS

# Rotas para o controlador Telefone
telefone_new:
    path:     /telefone/{pessoa_id}/new
    defaults: { _controller: CadpazBundle:Telefone:new }
    options:
        expose: true
# Fim das rotas para o controlador Telefone

# Rotas para o controlador Endereco
endereco_view:
    path:     /endereco/{id}/view
    defaults: { _controller: CadpazBundle:Endereco:view }

endereco_new:
    path:     /endereco/{pessoa_id}/new
    defaults: { _controller: CadpazBundle:Endereco:new }
    options:
        expose: true

endereco_edit:
    path:     /endereco/{id}/edit
    defaults: { _controller: CadpazBundle:Endereco:edit }

endereco_delete:
    path:     /endereco/{id}/delete
    defaults: { _controller: CadpazBundle:Endereco:delete }
# Fim das rotas para o controlador Endereco

# Rotas para o controlador Questionario
questionario_new:
    path:     /questionario/{pessoa_id}/new
    defaults: { _controller: CadpazBundle:Questionario:new }
    options:
        expose: true
        
questionario_save_to_session:
    path:     /questionario/sesssave
    defaults: { _controller: CadpazBundle:Questionario:saveToSession }
    options:
        expose: true
        
questionario_restore_from_session:
    path:     /questionario/sessrestore
    defaults: { _controller: CadpazBundle:Questionario:restoreFromSession }
    options:
        expose: true
# Fim das rotas para o controlador Questionario

# Rotas para o controador Caso
caso_new:
    path:     /caso/{pessoa_id}/new
    defaults: { _controller: CadpazBundle:Caso:new }
    options:
        expose: true
        
caso_view:
    path:     /caso/{id}/view
    defaults: { _controller: CadpazBundle:Caso:view }
    options:
        expose: true
        
caso_list_json:
    path:     /caso/list_json
    defaults: { _controller: CadpazBundle:Caso:listJson }
    options:
        expose: true    
#Fim das rotas para o controlador Caso

# Rotas para o controlador Atendimento
atendimento_new:
    path:     /atendimento/{caso_id}/new
    defaults: { _controller: CadpazBundle:Atendimento:new }
    options:
        expose: true

atendimento_view:
    path:     /atendimento/{id}/view
    defaults: { _controller: CadpazBundle:Atendimento:view }
    options:
        expose: true
# Fim das rotas para o controlador Atendimento

encaminhamento_new:
    path:     /encaminhamento/{atendimento_id}/new
    defaults: { _controller: CadpazBundle:Encaminhamento:new }
    options:
        expose: true

encaminhamento_list_json:
    path:     /encaminhamento/list_json
    defaults: { _controller: CadpazBundle:Encaminhamento:listJson }
    options:
        expose: true

relatorios_index:
    path:     /relatorios/index
    defaults: { _controller: CadpazBundle:Relatorios:index }
    options:
        expose: true

relatorios_casos:
    path:     /relatorios/casos
    defaults: { _controller: CadpazBundle:Relatorios:casos }
    options:
        expose: true
        
relatorios_encaminhamentos:
    path:     /relatorios/casos
    defaults: { _controller: CadpazBundle:Relatorios:encaminhamentos }
    options:
        expose: true
        
relatorios_idades:
    path:     /relatorios/idades
    defaults: { _controller: CadpazBundle:Relatorios:idades }
    options:
        expose: true
        
relatorios_sexos:
    path:     /relatorios/sexos
    defaults: { _controller: CadpazBundle:Relatorios:sexos }
    options:
        expose: true    

relatorios_cores:
    path:     /relatorios/cores
    defaults: { _controller: CadpazBundle:Relatorios:cores }
    options:
        expose: true

#configuracoes_index:
#    path:     /config/index
#    defaults: { _controller: DedraksConfigBundle:Default:index }
#    options:
#        expose: true

configuracoes_caso_tipo_new:
    path:     /config/caso/new
    defaults: { _controller: CadpazBundle:Configuracoes:newCasoTipo }
    options:
        expose: true

configuracoes_caso_tipo_edit:
    path:     /config/caso/{id}/edit
    defaults: { _controller: CadpazBundle:Configuracoes:editCasoTipo }
    options:
        expose: true

configuracoes_caso_tipo_delete:
    path:     /config/caso/{id}/delete
    defaults: { _controller: CadpazBundle:Configuracoes:deleteCasoTipo }
    options:
        expose: true
        
configuracoes_origem_new:
    path:     /config/origem/new
    defaults: { _controller: CadpazBundle:Configuracoes:new }
    options:
        expose: true