pessoa_index:
    path:     /pessoa
    defaults: { _controller: CadpazBundle:Pessoa:index }

pessoa_list:
    path:     /pessoa/list
    defaults: { _controller: CadpazBundle:Pessoa:list }

pessoa_busca:
    path:     /pessoa/busca
    defaults: { _controller: CadpazBundle:Pessoa:busca }

pessoa_new:
    path:     /pessoa/new
    defaults: { _controller: CadpazBundle:Pessoa:new }

atendimento_index:
    path:     /atendimento
    defaults: { _controller: CadpazBundle:Atendimento:index }
