# Rotas para o controlador Pessoa
pessoa_index:
    path:     /
    defaults: { _controller: CadpazBundle:Pessoa:index }

pessoa_list:
    path:     /pessoa/list
    defaults: { _controller: CadpazBundle:Pessoa:list }
    options:
        expose: true

pessoa_busca:
    path:     /pessoa/busca
    defaults: { _controller: CadpazBundle:Pessoa:busca }
    options:
        expose: true

pessoa_new:
    path:     /pessoa/new
    defaults: { _controller: CadpazBundle:Pessoa:new }
    options:
        expose: true

pessoa_view:
    path:     /pessoa/{id}/view
    defaults: { _controller: CadpazBundle:Pessoa:view }
    options:
        expose: true

pessoa_titulo_new:
    path:     /pessoa/{id}/titulo/new
    defaults: { _controller: CadpazBundle:Pessoa:newTitulo }
    options:
        expose: true

# Fim das rotas para o controlador Pessoa

# Rotas para o controlador CTPS
ctps_view:
    path:     /ctps/{pessoa_id}/view
    defaults: { _controller: CadpazBundle:CTPS:view }

ctps_new:
    path:     /ctps/{pessoa_id}/new
    defaults: { _controller: CadpazBundle:CTPS:new }

# Fim das rotas pra o controlador CTPS

# Rotas para o controlador Questionario
# Fim das rotas para o controlador Questionario


atendimento_index:
    path:     /atendimento
    defaults: { _controller: CadpazBundle:Atendimento:index }
