pessoa_index:
    path:     /pessoa
    defaults: { _controller: CadpazBundle:Pessoa:index }

pessoa_list:
    path:     /pessoa/list
    defaults: { _controller: CadpazBundle:Pessoa:list }
    options:
        expose: true

pessoa_busca:
    path:     /pessoa/busca
    defaults: { _controller: CadpazBundle:Pessoa:busca }
    options:
        expose: true

pessoa_new:
    path:     /pessoa/new
    defaults: { _controller: CadpazBundle:Pessoa:new }

pessoa_view:
    path:     /pessoa/{id}/view
    defaults: { _controller: CadpazBundle:Pessoa:view }
    options:
        expose: true

atendimento_index:
    path:     /atendimento
    defaults: { _controller: CadpazBundle:Atendimento:index }
