<?php

namespace CadpazBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasoRepository extends EntityRepository
{
    public function findAllDistinctOrderedByTotal()
    {
        //'SELECT c.nome as tipo, (select count(*) from caso ca where c.nome=ca.nome) as total from caso c group by c.nome '
        return $this->getEntityManager()
            ->createQuery(
                //'SELECT c FROM CadpazBundle:Caso c GROUP BY c.nome ORDER BY c.nome'
                    'SELECT c.nome, (SELECT COUNT(ca.nome) FROM CadpazBundle:Caso ca WHERE c.nome=ca.nome) as total FROM CadpazBundle:Caso c GROUP BY c.nome ORDER BY total DESC'
            )
            ->getResult();
    }
    
    public function countAll()
    {
        return $this->getEntityManager()
                ->createQuery(
                    'SELECT c.nome as tipo, (SELECT COUNT(ca.nome) FROM CadpazBundle:Caso ca WHERE c.nome=ca.nome) as total FROM CadpazBundle:Caso c GROUP BY c.nome ORDER BY total DESC'
                )
                ->getResult();
    }
}
