<?php

namespace CadpazBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EncaminhamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncaminhamentoRepository extends EntityRepository
{
    public function findAllDistinctOrderedByTotal()
    {
        //'SELECT c.nome as tipo, (select count(*) from caso ca where c.nome=ca.nome) as total from caso c group by c.nome '
        return $this->getEntityManager()
            ->createQuery(
                //'SELECT c FROM CadpazBundle:Caso c GROUP BY c.nome ORDER BY c.nome'
                    'SELECT e.encaminhado, (SELECT COUNT(en.encaminhado) FROM CadpazBundle:Encaminhamento en WHERE e.encaminhado=en.encaminhado) as total FROM CadpazBundle:Encaminhamento e GROUP BY e.encaminhado ORDER BY total DESC'
            )
            ->getResult();
    }
}
